spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  profiles:
#    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      name: ecommerce

    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/actuator/**
              - Method=GET,POST
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#          - id : user-service
#            uri : lb://USER-SERVICE
#            predicates:
#              - Path=/user-service/**
          - id : user-service
            # Eureka 에 등록된 서비스의 이름으로 로드 밸런싱
            # 만약 같은 서비스가 여러개 실행된다면 같은 서비스에 요청했을때 기본적으로 Round Robin
            uri : lb://USER-SERVICE
            # predicates:조건절
            predicates:
              - Path=/user-service/login
              - Method=POST
            filters:
              # Request Header 값 초기화
              - RemoveRequestHeader=Cookie
              # /user-service/{segment} -> /{segment} 로 변환
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
          - id : user-service
            uri : lb://USER-SERVICE
            predicates:
              - Path=/user-service/users
              - Method=POST
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
          - id : user-service
            uri : lb://USER-SERVICE
            predicates:
              - Path=/user-service/**
              - Method=GET
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
              - AuthorizationHeaderFilter
          # Catalog
          - id : catalog-service
            uri : lb://CATALOG-SERVICE
            predicates:
              - Path=/catalog-service/**
          # Order
          - id : order-service
            uri : lb://ORDER-SERVICE
            predicates:
              - Path=/order-service/**
          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/order-service/actuator/**
              - Method=GET
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/order-service/(?<segment>.*), /$\{segment}
          # First-service
          - id : first-service
            uri : lb://MY-FIRST-SERVICE
            predicates:
              - Path=/first-service/**
            filters:
#              - AddRequestHeader=first-request, first-request-header2
#              - AddResponseHeader=first-response, first-response-header2
              - CustomFilter
          # Second-service
          - id : second-service
            uri : lb://MY-SECOND-SERVICE
            predicates:
              - Path=/second-service/**
            filters:
#              - AddRequestHeader=second-request, second-request-header2
#              - AddResponseHeader=second-response, second-response-header2
              - name: CustomFilter
              - name: LoggingFilter
                args:
                  baseMessage: Hi,there.
                  preLogger: true
                  postLogger: true


server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh, info, prometheus
#token:
#  secret: Gs0pGmm9NJJfGkKxqzoxXDr3E4Pp9P3qGaHRrfwFO65MoSbVmwNE99UhB8hUE8VVQX1USwV7dJHogcH6CK1VKw==